apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-job
            image: cron-image:latest
            imagePullPolicy: Never
            args:
            - python
            - create_job.py
          restartPolicy: OnFailure